CREATE TABLE STATS (
        STAT_ID INT(11) NOT NULL AUTO_INCREMENT,
        STAT_DATE DATETIME NOT NULL,
        STAT VARCHAR(20) NOT NULL,
        VALUE INT(11) NOT NULL,
        PRIMARY KEY(STAT_ID)
);

DROP VIEW bestsellers_count;

CREATE VIEW BESTSELLERS_COUNT AS
    SELECT COUNT(*) AS COUNT FROM BOOKS
      WHERE BESTSELLER = 1;


USE KODILLA_COURSE;           -- [1]
DELIMITER $$

CREATE EVENT UPDATE_BESTSELLERS      -- [2]
    ON SCHEDULE EVERY 1 MINUTE -- [3]
    DO
    BEGIN
    CALL UpdateBestsellers();
    INSERT INTO STATS(STAT_DATE, STAT, VALUE)
    VALUES(CURDATE(), 'BESTSELLERS', (SELECT BESTSELLERS_COUNT.COUNT FROM BESTSELLERS_COUNT));
    COMMIT;
    END $$

DELIMITER ;

SHOW PROCESSLIST;

SELECT * FROM stats;

DROP EVENT UPDATE_BESTSELLERS;




